{{- if .Values.acapy.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "acapy.serviceAccountName" . }}
  labels:
    {{- include "acapy.labels" . | nindent 4 }}
  {{- with .Values.acapy.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
