{{- if not .Values.acapy.persistence.existingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "acapy.tails.pvc.name" . }}
  labels:
    {{- include "acapy.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
  {{- range .Values.acapy.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.acapy.persistence.size | quote }}
  {{- include "common.storage.class" (dict "persistence" .Values.acapy.persistence "global" .Values.global) | nindent 2 }}
{{- end}}
