{{- if .Values.tenant_proxy.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tenant_proxy.serviceAccountName" . }}
  labels:
    {{- include "tenant_proxy.labels" . | nindent 4 }}
  {{- with .Values.tenant_proxy.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
