{{- if .Values.ui.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tenant-ui.fullname" . }}
  labels:
    {{- include "tenant-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "tenant-ui.selectorLabels" . | nindent 4 }}
{{- end -}}
