name: Build & Deploy Tenant UI
on:
  workflow_dispatch:
    inputs:
      deploy_env:
        description: 'Target (github) environment for deployment: development, test, production'
        required: true
        default: 'development'
      ref:
        description: 'The branch, tag or SHA to checkout'
        required: false
        default: ''
      traction_api_endpoint:
        description: 'Traction API Endpoint'
        required: true
        default: 'https://traction-api-dev.apps.silver.devops.gov.bc.ca'
      instance_name:
        description: 'Instance name'
        required: true
        default: 'tenant-ui'
      traction_name:
        description: 'Traction instance name'
        required: true
        default: 'traction'

jobs:

  build_image:
    runs-on: ubuntu-20.04
    if: github.repository_owner == 'bcgov'
    steps:      
      - uses: actions/checkout@v2    
        with:
          ref: ${{ github.event.inputs.ref }}    
      
      - name: Build service
        uses: ./.github/actions/build_ui
        id: builder
        with:
          ref: ${{ github.event.inputs.ref }}
          context: './services/tenant-ui'
          image_name: ${{ github.repository_owner}}/traction-tenant-ui
          registry: ghcr.io
          registry_username: ${{ github.repository_owner}}          
          registry_password: ${{ secrets.GITHUB_TOKEN }}
    
    outputs:
      image_tag: ${{ steps.builder.outputs.image_tag }}

  deploy:
    environment: ${{ github.event.inputs.deploy_env }}
    runs-on: ubuntu-20.04
    needs: 
      - build_image
    if: ${{ always() && contains(needs.*.result, 'success') && !(contains(needs.*.result, 'failure')) && (github.repository_owner == 'bcgov') }}
    
    steps:  
      - uses: actions/checkout@v2  

      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          certificate_authority_data: ${{ secrets.OPENSHIFT_CA_CRT }}
          namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}

      - name: Run Helm
        run: |
          helm upgrade --install "${{ github.event.inputs.instance_name }}" -f ./deploy/tenant-ui/values-${{ github.event.inputs.deploy_env }}.yaml --set image.tag=${{ needs.build_image.outputs.image_tag }} --set traction.apiEndpoint="${{ github.event.inputs.traction_api_endpoint }}"  --set traction.pluginInnkeeper.existingSecret="${{ github.event.inputs.traction_name }}-acapy-plugin-innkeeper" ./charts/tenant-ui --wait

      - name: Restart Tenant-UI Pods
        run: |
          oc rollout restart deployment/${{ github.event.inputs.instance_name }}
      